# Generated by Django 3.2.9 on 2021-11-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Song_Type',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20),
        ),
    ]
