# Generated by Django 3.2.9 on 2021-11-30 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 30, 13, 9, 9, 422648), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], default='FREE', max_length=100),
        ),
    ]
