# Generated by Django 3.2.9 on 2021-12-23 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_profile_premium_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 24, 4, 18, 38, 218943), null=True),
        ),
    ]
